### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by Hirano-Tech** [Hirano-Tech/chat-space#12]
# IPアドレス
3.115.229.222

**Comment by mo1015** [comment]
平野さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**○サイドバーの「グループ名」、「最新メッセージ」に下線が入っている**
<img width="299" alt="修正" src="https://user-images.githubusercontent.com/62644781/80857526-d892d400-8c8d-11ea-8b0e-2e4f5fe899be.png">




修正でき次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by mo1015** [comment]
再提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
